### ISSUE TITLE
Running yarn install && calliope build in (at least) web/themes/chromatic fails in a Windows Lando on WSL2 environment

### ISSUE THREAD

**Issue by Boegie** [ChromaticHQ/calliope#14]
## Description

Discovered when trying to run `composer robo dev:refresh` on project `chromatichq.com`, but I'm pretty sure this will be the same on all projects that use `calliope`.

The above command fails on Windows OS using Lando on WSL2 in stage `composer robo theme:build default` with output:

```
theme build
===========

building theme at web/themes/chromatic
--------------------------------------

 [Exec] Running yarn build in web/themes/chromatic
yarn run v1.22.17
$ yarn calliope build
$ yarn install && calliope build
[1/4] Resolving packages...
success Already up-to-date.
$ symdeps
[12:16:22]
[12:16:23]
[12:16:23]
[12:16:27] ✓ Project config found!
[12:16:27]     Using file D:\htdocs\chromatichq.com\web\themes\chromatic\calliope.config.js.
[12:16:27] - No personalization options detected via .env file.
[12:16:27] ✓ Custom daemons found!
[12:16:27]     The following custom Gulp tasks will run alongside watch tasks:
[12:16:27]       - fractal
[12:16:32] ✓ Custom pipelines found!
[12:16:32]     The following custom or override Gulp tasks will run as part of your build:
[12:16:32]       - scripts
[12:16:32] ✓ Custom tasks found!
[12:16:32]     The following custom Gulp tasks are available:
[12:16:32]       - patterns
[12:16:32]       - preview
```

Stack trace:

```
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: spawn gulp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn gulp',
  path: 'gulp',
  spawnargs: [
    '--gulpfile',
    'D:\\htdocs\\chromatichq.com\\web\\themes\\chromatic\\node_modules\\@chromatichq\\calliope\\gulpfile.js',
    '--cwd',
    'D:\\htdocs\\chromatichq.com\\web\\themes\\chromatic',
    'build'
  ]
}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
error Command failed with exit code 1.
```

## To Reproduce

1. Run  `composer robo theme:build default` on project `chromatichq.com`
2. CLUNK

## Expected Behavior
A freshly build front-end

**Comment by Boegie** [comment]
PR incoming
